# Generated by Django 3.1.4 on 2020-12-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticated',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='authenticated',
            name='slug',
        ),
        migrations.AlterField(
            model_name='person',
            name='encodings',
            field=models.CharField(max_length=3000),
        ),
    ]
